// Generated by https://quicktype.io

export interface LastFMWeekChart {
  weeklytrackchart?: Weeklytrackchart
}

export interface Weeklytrackchart {
  "@attr": WeeklytrackchartAttr
  track: Track[]
}

export interface WeeklytrackchartAttr {
  user: string
  from: string
  to: string
}

export interface Track {
  artist: Album
  "@attr"?: TrackAttr
  mbid: string
  album: Album
  streamable: string
  url: string
  name: string
  image: Image[]
  date?: DateClass
}

export interface Album {
  mbid: string
  "#text": string
}

export interface DateClass {
  uts: string
  "#text": string
}

export interface TrackAttr {
  rank: string
}

export interface Artist {
  mbid: string
  "#text": string
}

export interface Image {
  size: Size
  "#text": string
}

export enum Size {
  Large = "large",
  Medium = "medium",
  Small = "small",
}
