import React from "react"
import { Link } from "gatsby"

// Generated by https://quicktype.io

interface Props {
  post: Post
}

export interface Post {
  node: Node
}

export interface Node {
  id: string
  frontmatter: Frontmatter
}

export interface Frontmatter {
  title: string
  date: string
  tags: string[]
  excert: string
  path: string
}

const PostPreview = ({ post }: Props) => {
  return (
    <Link to={post.node.frontmatter.path}>
      <div>
        <h2>{post.node.frontmatter.title} </h2>
        <h4>{post.node.frontmatter.date}</h4>

        <p> {post.node.frontmatter.excert} </p>
      </div>
    </Link>
  )
}

export default PostPreview
