import React from "react"

import "../../tailwindcss/tailwind.src.css"
import Layout from "./layout"
import SEO from "./seo"
import { useStaticQuery, graphql } from "gatsby"

// Generated by https://quicktype.io

export interface Data {
  data: DataClass
}

export interface DataClass {
  __typename: string
  markdownRemark: MarkdownRemark
}

export interface MarkdownRemark {
  id: string
  html: string
  timeToRead: number
  frontmatter: Frontmatter
}

export interface Frontmatter {
  date: string
  excert: string
  path: string
  tags: string[]
  title: string
}
const PostPage = ({ data }: Data) => {
  const { frontmatter, html } = data.markdownRemark

  return (
    <Layout>
      <SEO title={frontmatter.title} />
      <div className="max-w-4xl m-auto bg-gray-800 p-5">
        <h4>{frontmatter.date}</h4>
        <div dangerouslySetInnerHTML={{ __html: html }} />
      </div>
    </Layout>
  )
}

export const pageQuery = graphql`
  query($path: String!) {
    __typename
    markdownRemark(frontmatter: { path: { eq: $path } }) {
      id
      html
      timeToRead
      frontmatter {
        title
        date
        tags
        path
        excert
      }
    }
  }
`

export default PostPage
