import React from "react"

// Generated by https://quicktype.io

interface Props {
  post: Post
}

export interface Post {
  node: Node
}

export interface Node {
  id: string
  frontmatter: Frontmatter
}

export interface Frontmatter {
  title: string
  date: string
  tags: string[]
  excert: string
}

const PostPreview = ({ post }: Props) => {
  return <p> {post.node.id} </p>
}

export default PostPreview
